=head1 NAME

StatisticsCollector::Controller::Dashboard - Catalyst Controller

=head1 SYNOPSIS

    my $code = 'example';

=head1 DESCRIPTION

Presents a dashboard page for the regular user

=head1 METHODS

=cut

=head2 name_of_method( $arg, \%arg [, $optional ] )

description

=cut

=head1 AUTHOR

Wolfgang Kinkeldei

=head1 LICENSE

This library is free software. You can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
